FROM hypriot/rpi-node:6.10.0-alpine

WORKDIR /code
COPY tmp/ /code

RUN npm install --production

# Number of milliseconds between polling requests. Default is 1000.
ENV MS 1000

EXPOSE 8080

CMD ["node", "server.js"]
