FROM node:6.11.2-alpine

WORKDIR /app
COPY tmp /app

RUN npm install --production

# Number of milliseconds between polling requests. Default is 1000.
ENV MS 1000

EXPOSE 8080

CMD ["node", "server.js"]
