FROM aarch64/node:6.9.1-slim
COPY qemu-aarch64-static /usr/bin/qemu-aarch64-static
WORKDIR /code
COPY tmp/ /code

# Number of milliseconds between polling requests. Default is 1000.
ENV MS 1000

EXPOSE 8080

CMD ["node", "server.js"]
